In [3]:
import numpy as np
from osgeo import gdal, ogr
from sklearn import metrics

naip_fn = "D:/cbr/VP2/VP2_SoilMapping/CodeOutput/output_file_rgb.tif"

print(naip_fn)
driverTiff = gdal.GetDriverByName('GTiff')
naip_ds = gdal.Open(naip_fn)

test_fn = "D:/cbr/VP2/VP2_SoilMapping/Shapes/test.shp"
test_ds = ogr.Open(test_fn)
lyr = test_ds.GetLayer()
driver = gdal.GetDriverByName('MEM')
target_ds = driver.Create('', naip_ds.RasterXSize, naip_ds.RasterYSize, 1, gdal.GDT_UInt16)
target_ds.SetGeoTransform(naip_ds.GetGeoTransform())
target_ds.SetProjection(naip_ds.GetProjection())
options = ['ATTRIBUTE=id']
gdal.RasterizeLayer(target_ds, [1], lyr, options=options)

truth = target_ds.GetRasterBand(1).ReadAsArray()
pred_ds = gdal.Open('D:/cbr/VP2/VP2_SoilMapping/Processed/classified.tif')
pred = pred_ds.GetRasterBand(1).ReadAsArray()

idx = np.nonzero(truth)
cm = metrics.confusion_matrix(truth[idx], pred[idx])

print(cm)
print(cm.diagonal())
print(cm.sum(axis=0))

accuracy = cm.diagonal() / cm.sum(axis=0)




D:/cbr/VP2/VP2_SoilMapping/CodeOutput/output_file_rgb.tif
[[4 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 2 0 0 0]
 [0 0 0 8 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 5]]
[4 0 2 8 2 5]
[ 4  0  2 10  2  5]


C:\Users\ST1154~1\AppData\Local\Temp/ipykernel_15416/915678775.py:32: RuntimeWarning: invalid value encountered in true_divide
  accuracy = cm.diagonal() / cm.sum(axis=0)
